spring:
 application:
  name: config-default
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true

#actuator health exposure
management:
 endpoints:
  web:
   exposure:
    include: "*"
  health:
   show-details: always


  
